description: >-
  Mike Kutzma's Dev Log
baseurl: ""
url: "https://mikekutzma.github.io"
github_username: mikekutzma
timezone: America/New_York
permalink: /:categories/:year/:month/:day/:title
search: true
locale: "en-US"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-includes-cache

author:
  name             : Mike Kutzma
  bio              : "Mostly breaking things."
  location         : "New York"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mikekutzma"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:michaelkutzma@gmail.com"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mikekutzma"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:michaelkutzma@gmail.com"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
