author: Mike Kutzma
description: >-
  Mike Kutzma's Dev Log
baseurl: ""
url: "https://mikekutzma.github.io"
github_username: mikekutzma
timezone: America/New_York
permalink: /:categories/:year/:month/:day/:title

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
